### ISSUE TITLE
When will project 2 be published?

### ISSUE THREAD

**Issue by nevlunghavn** [anderkve/FYS3150#10]
Hi,
On the Canvas pages it now says, "Tilgjengelig etter 14. sep. 2021 0.00" in regard to project 2 so I'm wondering when the project will be published.

**Comment by anderkve** [comment]
Hi @nevlunghavn,

Sometime today, as soon as it's ready. Though, it might not be ready until sometime this afternoon/evening. I'll post a message on the course page when it's published.

**Comment by nevlunghavn** [comment]
Thanks
