### ISSUE TITLE
Memory issue for A and B matrices

### ISSUE THREAD

**Issue by LingoNMBU** [anderkve/FYS3150#100]
hey, 

I'm having issues with memory as the A and B matrices become large for problem 7. Initializing with a spatial resolution of 0.005 (giving matrices of 39601 x 39601)results in an out of  memory error. Is the thought to subdivide the matrices into smaller parts and then compute the multiplications and solutions for subsets of the space, or is it valid to reduce the spatial resolution( matrices for resolutions down to around around 0.007 work)?

**Comment by anderkve** [comment]
Hi @LingoNMBU!

Have you done problem 0? :) https://anderkve.github.io/FYS3150/book/projects/project5.html#problem-0

I would expect that the hint at the end of that problem would solve the potential memory challenge on most systems. If that isn't the case, you can just reduce the spatial resolution and comment on this in your report.

**Comment by LingoNMBU** [comment]
Thanks for the quick reply! It seems rushing through got the best of me :P
