### ISSUE TITLE
Hva er et "Algorithm environment"? interpret

### ISSUE THREAD

**Issue by Madssb** [anderkve/FYS3150#108]
Hi, 

In our feedback for project 4, we recieved a comment on the way we present the Metropolis-Hastings algorithm:
"the Metropolis-Hastings algorithm could be put in an Algorithm environment to increase the readability.".

What is an Algorithm environment? Is the comment suggesting Pseudo-code?

Best regards,
Mads

**Comment by anderkve** [comment]
Hi @Madssb!

It's referring to a TeX `\begin{algorithm} ... \end{algorithm}` environment, like demonstrated in the report template we provided.
