### ISSUE TITLE
Issue on page /book/using_git/setting_up_git_and_a_GitHub_repo.html

### ISSUE THREAD

**Issue by giammy00** [anderkve/FYS3150#110]
Hello! 
Here's a suggestion for little improvement to the tutorial.
I followed this tutorial when I took the course fys3150 back in autumn 2021. I have recently noticed a very little privacy issue which almost nobody probably cares about (and I reckon it's not something dramatic, but I am a little bit obsessed by these things, and there may be someone like me also in future years). When setting up the user email with `git config --global user.email xxx@domain` , it might be worth mentioning that in this way, that email will appear in every commit which the user does from their terminal.
So, anybody who has access to the repository (i.e. in principle, anybody on the internet if the repo is set to public), can do the following:

- clone the repository
- perform `git log` and see every committer's email

GitHub provides a [pseudo email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github) which can be used to prevent private email adresses from being exposed.  I realize our repo is not a _multibillion dollar code project_ and will probably be seen by no one apart from us and the TAs, so this is not the end of the world, but it turns out to be really hard to undo this when it happens. 
Thank you anyway for having such an amazing course!

**Comment by anderkve** [comment]
Hi @giammy00! Thanks a lot, this is really helpful! :)
