### ISSUE TITLE
Obscured submit button on Canvas

### ISSUE THREAD

**Issue by nevlunghavn** [anderkve/FYS3150#14]
This is not really an "issue" with FYS3150, but since others may be experiencing the same problem with Canvas, I'll mention is here. As can be seen in the attached screenshot, the "submit/upload/send" button is obscured by the "Kurschat" whatever it's called. I had to guess that the blue button was the  "submit/upload/send". If anyone knows how to get rid of the "Kurschat", please post a comment. I use Firefox on Linux. Scrolling does not help and I can see nothing in the preferences to allow me to remove the "Kurschat"
 
![Screenshot at 2021-09-27 19-07-07](https://user-images.githubusercontent.com/89741295/134954931-5d5e9d5e-353d-40bf-ba98-67d995da3079.png)

**Comment by sverrewn** [comment]
A temporary solution is to use the inspect element feature in the browser and delete html code until it disappears. If something goes wrong you can always just reload the webpage since you're just changing the code locally
