### ISSUE TITLE
Error when I try to export my arma::mat and arma::vec into binary files for plotting

### ISSUE THREAD

**Issue by dondondooooon** [anderkve/FYS3150#15]
I wrote 

arma_eigvec.save('armavec.bin');

where arma_eigvec is type arma::mat.

<img width="773" alt="Screen Shot 2021-09-27 at 21 03 50" src="https://user-images.githubusercontent.com/89593997/134969260-7c87a110-af2c-4be2-9265-c98932cd9b6e.png">

**Comment by anderkve** [comment]
Try using double quotes (") instead of single quotes ('). In Python it doesn't matter, but in C++ it does.
