### ISSUE TITLE
Ex. 10 time dependence and w_V

### ISSUE THREAD

**Issue by SaraPJensen** [anderkve/FYS3150#20]
In exercise 10, w_V is treated as a constant, whereas V, and thereby w_z, w_plus and w_min are time-dependent. However, we are asked to find the relationship between w_V and w_z, w_plus and w_min. In order to find this, I assume it is necessary to print out the values of w_z, w_plus and w_min, but at what time-step are we meant to do this? And is the relationship between them and w_V expected to be time-independent?

**Comment by anderkve** [comment]
Hi @SaraPJensen!

I probably should have clarified this in the text (I'll add a note about it), but the definition of w_z in Problem 10 remains the same as before, i.e. in terms of the *constant* V_0. (But in Problem 10 V_0 has a new value.) So the value of w_z, and thus w_plus and w_minus, remains *time-independent* also in problem 10.

Hope that helps!
