### ISSUE TITLE
Global errors

### ISSUE THREAD

**Issue by dondondooooon** [anderkve/FYS3150#21]
Jeg kom bare på en liten spørsmål...

Hvorfor er høyere global error bedre? 

Anders sa i en forelesning at RK4 hadde en global error på 4 orden slik at vi kunne bruke høyere h, og dermed er mer effektiv.

Hvorfor skal høyere orden i global error gjøre det mulig for å bruke et høyere tidssteg h?

**Comment by anderkve** [comment]
Hei @dondondooooon!

Husk at "høy orden" ikke nødvendigvis er det samme "stort tall". Her snakker vi om hvordan feilen oppfører seg som funksjon av steglengden h, når h --> 0. Steglengden h er altså et tall som er < 1, og dermed er høy orden <--> lavere tall (h > h^2 > h^3 > h^4 > ... )

At den globale feilen er O(h^4) betyr altså at feilen avtar som h^4 når h --> 0, så den avtar raskere med steglengde enn en metode som hadde f.eks. O(h^3) global feil.
