### ISSUE TITLE
mean values

### ISSUE THREAD

**Issue by raggsokker** [anderkve/FYS3150#23]
Maybe I am misunderstanding something, but it is "logical" to compare the empirical mean (1/N * sum x) to the mean one gets from the Boltzmann distribution? In project 4 problem 1) b), those two different mean values for energy seem to disagree with each other.

**Comment by anderkve** [comment]
Hi @raggsokker! 

Hmm, not sure I fully understand the question. There is no sample mean involved in problem 1 b) (You haven't done any form of sampling yet.) 

Also, in case this could be the source of the confusion: Keep in mind that the Boltzmann distribution is not a pdf for *energy*, its a pdf for *states* (discussed in the lecture on Friday). So make sure you are summing over the correct thing when finding the analytical expression for the expectation value <\epsilon> ...
