### ISSUE TITLE
Strange behaviour in y-direction

### ISSUE THREAD

**Issue by hafos** [anderkve/FYS3150#24]
We get quite some strange behaviour and are not able to pin point what could be the cause. Should we not see a greater spread in the y-direction? Have anyone had similar results which found out what was the cause?

Edit: We have checked the indexing, the making of A and B, tranforming u to U and solving the equation. All seems to be as it should, yet we get these results...

![double_slit_bug](https://user-images.githubusercontent.com/51909733/145275488-5a34bff4-dcfd-431d-b958-683b6bc58269.gif)

**Comment by anderkve** [comment]
Hi @hafos! 

There's definitely something funny going on :) How does it look when you run without the double-slit potential switched on?

Also, do you have a link to the code that produced this result? I might have time to take a quick look later.

**Comment by hafos** [comment]
This is what we get without any potential:
![no_potential_double_slit](https://user-images.githubusercontent.com/51909733/145278523-e333030c-a7cb-4c99-b312-cf39ed9f50e3.gif)
Code is in the repo:
https://github.com/hafos/FYS4150/tree/main/project5

Just compile main_simulation.cpp with the flags in the README and the run ./main_simulation.exe with one of the configurations as explained in the README. plot_simulation.py creates the animation.

**Comment by anderkve** [comment]
Thanks for the link! I haven't tried running your code, but I spotted one thing that looks like a problem, in `CrankNicolson.cpp`:

```
  // Insert diagonals with only r's
  for (int j=0; j<N2-3; j++)
  {
    A(j, j+3) = -r;
    A(j+3, j) = -r;
    B(j, j+3) = r;
    B(j+3, j) = r;
  }
 ```
I suspect that you want to reconsider the "+3" you use everywhere. Keep in mind that the example A and B matrices given in the project description were only examples for a specific value of M-2... :)  In other words, try to think about which u_{i,j} terms from Eq. 25 that these r-terms correspond to, and where they have to end up in the A and B matrices when you make the matrix --> vector change u_{i,j} --> u_k.

**Comment by hafos** [comment]
Derp. Thanks a lot!

Just changing to j+N where N=M-2 we get this beaute:
![double_slit_fixed](https://user-images.githubusercontent.com/51909733/145286932-3b147c5d-61bd-4429-8a8c-fd5573ef8f8e.gif)

**Comment by anderkve** [comment]
Nice! :)
