### ISSUE TITLE
Relativity

### ISSUE THREAD

**Issue by hafos** [anderkve/FYS3150#26]
Are there implications of using a "non-relativistic" particle as opposed to a relativistic one like photons we should want to mention?

Is this approach only limited to the non-relativistic case?

**Comment by anderkve** [comment]
Yes, the single-particle Schrödinger equation that we solve is only valid for non-relativistic particles. One way to see this is that it is based on the non-relativistic expression for the total energy of a particle: E = p/(2m) + V. To take into account relativity we need equations that agree with the relativistic expression for the particle energy: E = sqrt( (pc)^2 + (mc^2)^2 ) + V. Going down this road is historically what eventually led to the formulation of quantum field theory, which is the type of theories used in modern particle physics.

Here are some starting points if you want to dig deeper into this:
- https://en.wikipedia.org/wiki/Relativistic_quantum_mechanics 
- https://en.wikipedia.org/wiki/Relativistic_wave_equations
