### ISSUE TITLE
Find lab partners

### ISSUE THREAD

**Issue by anderkve** [anderkve/FYS3150#29]
If you are looking for lab partners, you can use this thread to get in touch with other students in the course. (Or use the discussion system on Canvas, if you prefer.)

**Comment by deryaaricigil** [comment]
Hello! My background is chemistry and I would love to collaborate. My email is deryaa@uio.no.

**Comment by sunnikbe** [comment]
Anyone who was thinking of working alone wanna work with me? :)

**Comment by larsfop** [comment]
> Anyone who was thinking of working alone wanna work with me? :)

If you are still looking for a partner, I am more than willing

**Comment by Freiamannen** [comment]
> Anyone who was thinking of working alone wanna work with me? :)

If you are looking for a third person (or if anyone else are looking for someone to collaborate with), I am then interested.

**Comment by multiib** [comment]
Hey! Does somebody want to work with my on project 4? :)
