### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by JohanCarlsen** [anderkve/FYS3150#32]
How can I label my issues on this page?
It says in the post earlier that I have to select `Labels` from the menu on the right, but all it says is `None yet`...

**Comment by anderkve** [comment]
Click the little wheel to the right where it says "Labels". Then click the relevant labels and then click somewhere else to remove the labels window. Then you should get the correct labels.

**Comment by JohanCarlsen** [comment]
I cant fint the wheel you're mentioning. I have no wheel there :(

**Comment by anderkve** [comment]
Ah, looks like it requires write access to the repository to do so. So that means I'll just have to label the issues myself. Thanks for testing!

**Comment by JohanCarlsen** [comment]
No problem! Then you can set both this issue and the one about fractions to solved 👍
