### ISSUE TITLE
using continues function for g(x). 

### ISSUE THREAD

**Issue by felofix** [anderkve/FYS3150#33]
Can I use the f(x) = 100*e^(-10x) function directly when creating the g-vector in problem 7? Or do I have to discretize this function also? Thanks :)

**Comment by mikkelme** [comment]
You use the function "directly" but you should use the discretized x elements such that  g[i] = h^2 * f(x[i]).

**Comment by anderkve** [comment]
EDIT: Ah, I see @mikkelme  beat me to it! :D  My answer below.

Hi @felofix!

Not entirely sure I understand the question, but when creating the elements of the `g` vector you can certainly directly call C++ code of the form `100. * std::exp(-10. * x[i])`. Of course, that expression alone is not all that's needed for the elements of `g`  -- but you have probably figured that out already :) 

Note that `std::exp` lives in the `<cmath>` standard header, so you have to include that. (See here for details: https://en.cppreference.com/w/cpp/numeric/math/exp)

**Comment by felofix** [comment]
absolutely, it was about the function specifically. thanks :)
