### ISSUE TITLE
Adding a Github token

### ISSUE THREAD

**Issue by nevlunghavn** [anderkve/FYS3150#4]
Not having much luck with this. It looks like this is no longer optional on github, so we have to get it working. I've tried:

1. following the instructions for linux at https://anderkve.github.io/FYS3150/book/using_git/setting_up_git_and_a_GitHub_repo.html with no luck. Generating the token went well, running the command "git config --global credential.helper store" returned no output (no error or anything else). Running command, "git pull" just returns, "Already up to date." in the repo which I've already cloned. At no point am I prompted for my github user name. My fys3150 repo is public, so I would not expect to be asked for a username either.

Any help would be appropriated.

**Comment by reneaas** [comment]
Hi, try creating a file and add a single line of content, e.g "this is a line". 

Now run

git config --global credential.helper store

Then add, commit and push the file. Once you attempt to push, git will require authentication. Type in your github username and paste in your token as a replacement for a password. 

This should fix the problem.

**Comment by nevlunghavn** [comment]
That did the trick. Thanks very much @reneaas
