### ISSUE TITLE
is it possible (or perhaps plausible) that a cpp program compiles, but the executable doesnt run on 1 computer, but not on another?

### ISSUE THREAD

**Issue by Madssb** [anderkve/FYS3150#40]
Hi, attempting to compile, and execute the program one of my collaborators have written. This however gives me an error i've never seen upon attempting to run the executable:
```
$ ./main 
malloc(): corrupted top size
Aborted (core dumped)
```
I have no idea where to start debugging. 
EDIT:
forgot to include my question. Is it possible that it succesfully ran for my collaborator, because he uses windows and possibly an IDE?

**Comment by Madssb** [comment]
it turns out the executable never actually succesfully ran, oops.

**Comment by anderkve** [comment]
Hi @Madssb,

I'm afraid I don't have time to look into this in detail now, but one quick suggestion is to look into array indices. malloc (= memory allocation) errors typically come from writing outside the bound of a raw C-style array. This can corrupt part of the memory, leading to a crash at some later point during the run. 

Whether it actually leads to a crash or not in a given run or on a given computer can depend on many other things, e.g. the current state of the memory. But if it happens at all it means that there is a bug in the code.

So my guess is that you have some index mistake somewhere. (But without seeing the code, this is mostly guesswork.)

**Comment by Madssb** [comment]
This was indeed the issue!
