### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by multiib** [anderkve/FYS3150#41]
Hello!
Is it ok to host my repo on UiO's GitHub pages or should it be on the standard version of GitHub?

PS: I also noticed that the due date of project 2 is Monday, September 27th. The 27th is a Tuesday so which one is it? :)

**Comment by anderkve** [comment]
Hi @multiib!

>  Is it ok to host my repo on UiO's GitHub pages or should it be on the standard version of GitHub?

It's perfectly fine to use UiO's GitHub pages. 

> PS: I also noticed that the due date of project 2 is Monday, September 27th. The 27th is a Tuesday so which one is it? :)

Ah, thanks for spotting that. :) The deadline will be the *Tuesday* -- I'll fix the typo in the project 2 description.
