### ISSUE TITLE
Problem with project 2 problem 1:U(x) == U(x^)?

### ISSUE THREAD

**Issue by DavidSvejda2507** [anderkve/FYS3150#43]
The function U(x) in equation 4 of project 4 is a different function from U(x<sup>^</sup>) in equation 5. The domain of the first function is [0,L], whereas the second function has domain [0,1]. The fact that these functions are different but the same notation is used is confusing, and the function of x<sup>^</sup> has not been defined. I propose to fix this by renaming the function of x<sup>^</sup>, for example to U<sup>^</sup>(x<sup>^</sup>), and by defining the function by U<sup>^</sup>(x<sup>^</sup>) = U(x).

**Comment by anderkve** [comment]
Yes, agreed -- I'll fix that late today. Thanks for spotting it!

**Comment by DavidSvejda2507** [comment]
As far as I can tell this hasn't been addressed in the project

**Comment by anderkve** [comment]
Ah, I forgot about it. Thanks for the reminder -- I've added a couple of comments now.
