### ISSUE TITLE
Referencing course material

### ISSUE THREAD

**Issue by nevlunghavn** [anderkve/FYS3150#5]
What is the preferred way to reference (BibTeX) lecture notes, lecture videos for the course and this repository?

**Comment by evenmn** [comment]
Hi,

BibTeX has a @misc entry for online sources. It can be used to cite both the lecture notes, lecture videos and GitHub repo. 

How to cite introduction lecture:

@misc{lecture_video1,
        title = {Lecture Video 1},
        date = {2021},
        organization = {UiO},
        author = {Anders Kvellestad},
        url = {https://www.uio.no/studier/emner/matnat/fys/FYS3150/h21/forelesningsvideoer/additional_introduction_lecture.mp4?vrtx=view-as-webpage},
}

How to cite GitHub Repository (at a given commit):

@misc{fys3150_github,
  author = {Anders Kvellestad},
  title = {FYS3150},
  year = {2021},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/anderkve/FYS3150}},
  commit = {d8e6259f8128448a9846c31d7ca03083749166b5}
}

Does this answer your question? You are free to choose citation style yourself :)

Best regards,
Even

**Comment by nevlunghavn** [comment]
That answers my question. Thank you.
