### ISSUE TITLE
Installere Armadillo / få Armadillo til å fungere

### ISSUE THREAD

**Issue by ivarlon** [anderkve/FYS3150#51]
Windows-bruker her, jeg sliter med å få Armadillo til å fungere og lurer på om installasjonen min ikke er optimal. Armadillo funket fint i prosjekt 1 når man bare trengte arma objekt, men tuller nå når jeg bruker metoder som eig_sym. Jeg får opp en feilmelding når jeg linker:

(.text._ZN4arma6lapack5syevdIdEEvPcS2_PiPT_S3_S5_S5_S3_S3_S3_S3_[_ZN4arma6lapack5syevdIdEEvPcS2_PiPT_S3_S5_S5_S3_S3_S3_S3_]+0x5d): undefined reference to `dsyevd_'

I forsøket på å fikse dette har google-søkene blitt stadig mer obskure, og jeg ser ikke lys i enden av tunnelen. Så jeg lurer på om det fins en smertefri måte å installere Armadillo på, sånn at den ikke skaper trøbbel og skjønner hvor f.eks. OpenBLAS og LAPACK osv. befinner seg.

**Comment by anderkve** [comment]
Hei @ivarlon!

Jeg antar du bruker WSL, altså at du fulgte Linux-oppskriften vår for å innstallere Armadillo, OpenBLAS og LAPACK på Linux-delen av maskinen din. (Oppskriften herfra: https://anderkve.github.io/FYS3150/book/getting_ready/linux_users.html )
Det er som regel helt smertefritt. Eller har du innstallert Armadillo på Windows og prøver å bruke den?

Kunne du sendt de eksakte g++-kommandoene du bruker for kompilering og linking, sammen med all skjermoutput?

Og en ting til: hva slags output får du om du kjører disse to kommandoene?

```
dpkg -L libblas-dev
``` 

```
dpkg -L liblapack-dev
```

**Comment by ivarlon** [comment]
Ja, jeg bruker WSL, men jeg installerte Armadillo ved å laste ned et komprimert arkiv fra den offisielle nettsiden og så brukte jeg cmake i Linux-terminalen. Jeg får nemlig feilmeldinger når jeg forsøker å installere pakkene etter kursets offisielle oppskrift:

`Package libopenblas-dev is not available, but is referred to by another package.`
`This may mean that the package is missing, has been obsoleted, or`
`is only available from another source `
`E: Package 'libopenblas-dev' has no installation candidate`
`E: Unable to locate package libarpack2-dev`
`E: Unable to locate package libsuperlu-dev`
`E: Unable to locate package libarmadillo-dev`
`E: Unable to locate package libomp-dev `

Jeg har fått installert en annen versjon av BLAS, men selv med den ville ikke Armadillo funke. Jeg forsøkte også å laste ned OpenBLAS via git men det ble bare kaos. xD

**Comment by anderkve** [comment]
Sitter på et tog, så svarene blir litt korte :)

To ting:

- Argumentet `-larmadillo` er et argument som har med linkingen, ikke kompileringen å gjøre. Så det må inkluderes i linke-kommandoen din, ikke kompileringskommandoen. Jeg tipper det vil løse problemet.
- Dersom problemet ikke løses, forsøk å innstallere BLAS med kommandoen `sudo apt install libblas-dev`

**Comment by ivarlon** [comment]
![skjermbildee2](https://user-images.githubusercontent.com/113121712/192288077-7c627825-a7f9-4cff-b665-1965c8952d29.PNG)

g++ skjønte ikke -larmadillo i linkingen heller. :-/
Får opp at jeg har installert libblas allerede.

**Comment by anderkve** [comment]
Ah, gikk litt fort i svingene her: jeg ser du har innstallert Armadillo i en egen mappe (`/mnt/c/Users/L390/cpp_packages/armadillo-11.2.4/`) i stedet for i en system-mappe, jf denne delen av README.md:
```
**Caveat:** if Armadillo is installed in a non-system directory,
make sure that the C++ compiler is configured to use the `lib` and `include`
sub-directories present within this directory.
```
Det betyr at jeg tipper du har en mappe `/mnt/c/Users/L390/cpp_packages/armadillo-11.2.4/lib` der selve det kompilerte Armadillo-biblioteket ligger. Stemmer det? I så fall kan du forsøke dette som linkekommando:
```
g++ problem2.o -o problem2.exe -L/mnt/c/Users/L390/cpp_packages/armadillo-11.2.4/lib -larmadillo
```

Jeg tror vi bør løse problemet med at du ikke får linket til Armadillo-biblioteket før vi løser problemet med at Armadillo ikke finner BLAS, men det vil være interessant å se hva resultatet av denne kommandoen er:

```
dpkg -L libblas-dev
```

**Comment by anderkve** [comment]
Hvilken cmake-kommando kjørte du da du innstallerte Armadillo i mappen `armadillo-11.2.4`? 

Jeg gjorde akkurat en test der jeg innstallerte Armadillo med cmake-metoden i en mappe `test` (i min Armadillo-mappe), og inne i den `test`-mappa finner jeg både en `include`-mappe og en `lib`-mappe.

Her er kommandoene jeg kjørte: 
```
cmake . -DCMAKE_INSTALL_PREFIX:PATH=/home/anders/physics/temp/armadillo-11.4.0/test
make install
```

og her er det resulterende innholdet i mappen `/home/anders/physics/temp/armadillo-11.4.0/test`:

```
anders@anders-xps15:~/.../armadillo-11.4.0/test$ ls -l
total 12
drwxr-xr-x 3 anders anders 4096 sep.  26 16:21 include
drwxrwxr-x 3 anders anders 4096 sep.  26 16:21 lib
drwxrwxr-x 3 anders anders 4096 sep.  26 16:21 share
```
der undermappen `lib` inneholder selve biblioteket `libarmadillo.so`

**Comment by ivarlon** [comment]
Kjørte bare `cmake . ` for å installere, men jeg fant ikke noen `lib`-mappe, uansett hvor mange ganger jeg kjører cmake...

**Comment by ivarlon** [comment]
Kjørte 'sudo make install' og nå skjedde det ting, ser ut som `lib` eksisterer i en system-mappe. Men får opp samme gamle error:
![skjermbilde](https://user-images.githubusercontent.com/113121712/192582444-04f62507-1c1a-460d-a1a1-2341f561699c.PNG)

**Comment by anderkve** [comment]
Hei igjen -- Jeg var opptatt i hele går, så kunne ikke svare da.

> Kjørte bare cmake . for å installere, men jeg fant ikke noen lib-mappe, uansett hvor mange ganger jeg kjører cmake...

Ah, men om du bare kjører `cmake`-kommandoen og ikke den etterfølgende `make`-kommandoen så er det ikke så rart at det ikke dukket opp noen `lib`-mappe. (Cmake-steget er typisk bare et konfigurasjonssteg. Selve kompileringen og linkingen av Armadillo-biblioteket skjer i `make`-steget.) Pass på å lese instruksene i Armadillos README.md nøye :) Både cmake- og make-kommandoen er nevnt i innstallasjonsveiledningen i avsnitt 5a.

> Kjørte 'sudo make install' og nå skjedde det ting, ser ut som lib eksisterer i en system-mappe. Men får opp samme gamle error:

Nå vet vi i det minste at du får linket til den versjonen av Armadillo som du selv har kompilert. Det er fremskritt. 

I avsnitt 6 i README.md står det litt om kompilering og linking -- har du forsøkt å bruke `ARMA_DONT_USE_WRAPPER` og linke direkte til BLAS og LAPACK, som beskrevet der? Det er også nevnt her, under "Linking" i Armadillos FAQ: https://arma.sourceforge.net/faq.html Det tredje punktet og det siste punktet under "Linking" kan være verdt å prøve.

**Comment by ivarlon** [comment]
> har du forsøkt å bruke `ARMA_DONT_USE_WRAPPER` og linke direkte til BLAS og LAPACK, som beskrevet der?
Ok det funka, takk!

Og ikke nok med det, nå funker også de kommandoene jeg kjørte i forrige innlegg, så jeg er muligens enda mer forvirret... Men satser på at det ikke oppstår problemer igjen.

**Comment by anderkve** [comment]
Godt å høre at det fungerer!
