### ISSUE TITLE
Project2: what to write for Problem 2-4?

### ISSUE THREAD

**Issue by leahelha** [anderkve/FYS3150#52]
What should we write about in our report for Problem 2-4, since the tasks only ask us to write a code that does X, but no qualitative questions?

**Comment by anderkve** [comment]
Hi @leahelha!

For these problems, you can just write a couple of sentences per problem, where you say in which file on the GitHub repository we can find the relevant code, and state whether the result of the test is as expected or not.

In a more proper project report like for Projects 3--5 (i.e. not just a problem set), tests like those in Problem 2--4 would correspond to what we could call "validation tests" or "unit tests" of the code. In a such report it would be natural to discuss these (briefly!) in the methods section of the report, or in an appendix.

**Comment by leahelha** [comment]
Hi Anders!
Thank you, that makes sense!
