### ISSUE TITLE
About the relative error 

### ISSUE THREAD

**Issue by JohanCarlsen** [anderkve/FYS3150#61]
Hi!
I'm having some trouble understanding the results I get for computing the relative error with the 5 different values of $h$.
For a simulation of $5\,\mu s`, this is what I get for RK4:
[relerror_RK4.pdf](https://github.com/anderkve/FYS3150/files/9752135/relerror_RK4.pdf)
Perhaps I'm calculating the error wrong?

**Comment by anderkve** [comment]
Hi @JohanCarlsen!

This does indeed look a bit strange. How are you computing the error? 

Note: This problem is now updated with a specific list of four (not five) stepsizes to use.

**Comment by JohanCarlsen** [comment]
Ive fixed it now, sorry for not closing issues as oæI move on 😅
