### ISSUE TITLE
Large differences between analytical and simulated solution

### ISSUE THREAD

**Issue by Flune** [anderkve/FYS3150#68]
![image](https://user-images.githubusercontent.com/70208937/197405816-2eacfbcd-168d-4365-98cf-95a2f2bf3ab4.png)

I have a big difference in the analytical and simulated solution. The image above shows the analytical and simulated particle in the x/y plane. I'm not sure which of these two are actually wrong, or if we are supposed to have this large of a difference. Is it the analytical or the simulated solution? The analytical solution of the particle seems to be moving a lot faster.

![image](https://user-images.githubusercontent.com/70208937/197405958-c3d13584-611a-4884-92cb-3a85c6bf7ef2.png)

This is the function I use for the analytical solution, in case it is of interest.

**Comment by anderkve** [comment]
Hi @Flune!

The large discrepancy is indeed surprising. I suspect it's the numerical solution that is the problem. 

Is this using the RK4 method? Keep in mind that there are a lot of factors of 0.5 involved in that algorithm, so perhaps you are missing such a factor somewhere? I'm just guessing based on the fact that from your plot it looks like the numerical solution is progressing about twice as fast as the analytical one.

Feel free to provide a link to the your code on GitHub -- then either me or one of the other teachers might have time to take a quick look sometime tomorrow. (No guarantees, though!)

**Comment by anderkve** [comment]
Another possible source of error that could give a time evolution that is about twice too fast: In the RK4 algorithm, if you have updated the positions/velocities of the particles in your trap in order to compute the various k's you need, make sure that the final update expressions for position/velocity still uses the old positions/velocities from the previous time step.

**Comment by anderkve** [comment]
One more thing, since you are computing the analytical solution in Python, while the numerical solution presumably comes from your C++ code: make sure that all numbers match across the two codes (e.g. the magnetic field strength), and make sure that the timesteps match.

**Comment by Flune** [comment]
It has been solved. Your first hunch was correct, a factor was missing. Thank you :)
