### ISSUE TITLE
Extentions

### ISSUE THREAD

**Issue by multiib** [anderkve/FYS3150#69]
Hi
What are the routines regarding extensions of project deadlines if you get sick?

**Comment by anderkve** [comment]
Hi, 

Without a doctor's note we can only give up to a couple of days extension of the deadline. With a doctor's note we can give longer extensions.

**Comment by multiib** [comment]
Alright, is there a form to fill out or should I send a mail to someone? :)

**Comment by anderkve** [comment]
No form -- you can just email me directly.
