### ISSUE TITLE
To cite or not to cite?

### ISSUE THREAD

**Issue by nigarabbasova** [anderkve/FYS3150#72]
Hi Anders! 

Just to double check - did you say that we were allowed to cite the text for Project 3 from the course website? For example, the equations of motion for two particles (eqs. 18,19 and 20)? 

Thank you for your help! :)

**Comment by anderkve** [comment]
Hi @nigarabbasova!

Indeed, you're allowed to cite the project description page. 

If you have time I would also encourage you to look up other sources for information on Penning traps. For instance, you might find book chapters or articles discussing some of the many uses of Penning traps, which might be something worth mentioning with a sentence or two in the introduction section of your report, as motivation for why the topic is important.

Good luck with finishing the report :)

**Comment by nigarabbasova** [comment]
Awesome, thank you so much! :)
