### ISSUE TITLE
Histograms 

### ISSUE THREAD

**Issue by augude** [anderkve/FYS3150#75]
Hi, 
I am having some troubles with my histograms of the energies. I have run 1 000 000 MC cycles for the 20x20 case and recorded the energy for each step. The histogram for the energy at T = 2.4 seems reasonable, but T = 1.0 seems far too dominated by the lowest energies. The histograms below have 500 bins but reducing/increasing the number of bins does not alter the histograms significantly. Also, the histograms look more or less the same if I start from an unordered or an ordered state. Is this expected, or is something wrong for T = 1.0? Do I just need even more samples?
![energyHists](https://user-images.githubusercontent.com/102254082/198849984-fe613d8b-96b0-4002-91db-78217b73dd32.png)

**Comment by anderkve** [comment]
Hi @augude!

> The histogram for the energy at T = 2.4 seems reasonable, but T = 1.0 seems far too dominated by the lowest energies.

Are you sure the T=1.0 histogram is unreasonable? (It's not obvious to me that it is!) Did you have any expectation for what it should look like?

A couple of things that might help in thinking about this:
- Note that we ask you to plot the histogram of *energy per spin* $(\epsilon)$, not energy directly. The shapes will of course be similar, but it may be easier to judge if the result is reasonable when you see that plot.
- Reducing the bin size further shouldn't change anything -- keep in mind that that the set of possible $\epsilon$ values is not continuous. And if you think about it closely, you probably know something about exactly which $\epsilon$ values are possible -- which may help you judge whether your histogram is reasonable or not. :)

> Also, the histograms look more or less the same if I start from an unordered or an ordered state. Is this expected, or is something wrong for T = 1.0?

What do you think? Hint: What is the MCMC method fundamentally supposed to do for us? When things are working and we are collecting enough samples, *should* the distribution of samples we end up with depend on the starting point?

**Comment by augude** [comment]
Thanks for the reply! I was just a bit puzzled by the skewness of the histogram, but I guess it makes sense that the lowest energy sates are by far the most probable at low temperatures.

**Comment by anderkve** [comment]
While we don't require you do do so in the project, now that you have the code set up to do it, you are of course very welcome check what the energy distribution looks like for some intermediate temperatures between T=2.4 and T=1.0. That might be useful to understand the evolution of the energy distribution as temperature decreases, and whether that seems physically reasonable.
