### ISSUE TITLE
About the energy difference

### ISSUE THREAD

**Issue by JohanCarlsen** [anderkve/FYS3150#76]
Hi! 
I've been trying to find the five values that $\Delta E$ can take, and ended up with the expression $$\Delta E=\pm2J\sum_k^Ns_k$$ I assume that the sum is the same as $M$(?), but $M$ can take many values, no?

**Comment by JohanCarlsen** [comment]
Hm. Okay. I have done this:
$
\begin{align}
\Delta E = -J\sum_{<kl>}^Ns_k^1s_l^1+J\sum_{<kl>}^Ns_k^0s_l^0
\end{align}
If only one spin (eg. $s_l$) flips, then $s_k^1=s_k^0$, and $s_l^1=\pm1$ and $s_l^0=\pm1$. This means that if $s_l^1=1$, then $s_l^0=-1$ and vice versa. This led me to 
$$\Delta E=-J\sum_{<kl>}^Ns_k(s_l^1-s_l^0)=2Js_l^1\sum_k^Ns_k$$
$

**Comment by JohanCarlsen** [comment]
Jeez, that did not format as intended.

**Comment by JohanCarlsen** [comment]
But you are saying that this is not correct, if so why? I thought I was on to something :'D

**Comment by JohanCarlsen** [comment]
Oh wait, is $\Delta E$ the energy difference of a *single particle* due to *its* flipping???

**Comment by anderkve** [comment]
The "energy shift due to *flipping a single spin*", as the project description says. :) The energy change $\Delta E$ is still an energy change in the *total system energy* $E$ (we don't discuss single-particle energies), but it's the energy change caused by flipping *one single spin* in the lattice.

**Comment by JohanCarlsen** [comment]
Then I'm back to not understanding why my first expression is not correct. The energy is given as a sum over all neighboring spin pairs, so the difference has to be a sum over all spins as well.

**Comment by anderkve** [comment]
If I understand your notation correctly, I think you have mathematically described the situation where we *flip one spin for each pair of interacting spins*. But the situation you should be describing is *flip one spin in the entire lattice*. That is, all but four of the spin pairs in the lattice will be completely unaffected by the flip.

**Comment by JohanCarlsen** [comment]
Aha! Thank you!

**Comment by anderkve** [comment]
You're welcome -- good luck with the project! :)
