### ISSUE TITLE
Specific heat capacity at $T = T_C$ 

### ISSUE THREAD

**Issue by augude** [anderkve/FYS3150#80]
Hi, 
The project description states that the specific heat capacity for an infinite 2D model behaves as 
$$C_V \propto |T - T_C(L = \infty)|^{-\alpha},$$
with $\alpha = 0$. What does this even mean? Something raised to the power of $0$ is just $1$? I read in the original paper from Onsager that "The specific heat becomes infinite at this critical point", but I do not get infinite when I substitute $T = T_C$ in the equation above unless I am missing something elementary.

**Comment by anderkve** [comment]
Hi @augude!

Thanks for asking this question. I thought I had added a note about it in the project description, but apparently forgot. (Will do so tomorrow.) I'll take some minutes to discuss it in the lecture tomorrow. But the short summary is that "critical exponent = 0" is just the power-law way of saying that it diverges *logarithmically*. That is, it diverges, but more slowly than any power law with an exponent > 0.

**Comment by augude** [comment]
Thanks!
