### ISSUE TITLE
Figure titles?

### ISSUE THREAD

**Issue by nigarabbasova** [anderkve/FYS3150#87]
Hi Anders!

We are a little bit confused about including titles of figures in our reports. In one report, we have been told that we should be including figure titles, and in the other one, we have been told that we should not be. What is the official stance on this? 

Thank you :)

**Comment by anderkve** [comment]
Hi Nigar!

Hehe, sounds like you've hit upon one of the inevitable subjective aspects of judging reports. :) 

While I wouldn't call it an official stance, my recommendation is to *not* include plot titles. (I'll email the other teachers so we're a bit coordinated on this.) At least within my own field of particle physics, plots almost never come with titles. 

However, in my field it is very common to add lots of text labels *inside* the plot frame. I personally find this more useful and elegant than plot titles. Just to pick some random examples, see for instance: 

- Figs. 6 and 7 of https://arxiv.org/pdf/1808.10465.pdf
- Fig. 3 of https://arxiv.org/pdf/2211.07665.pdf
- Fig. 3 of https://arxiv.org/pdf/2211.08028.pdf

But don't spend too much time on this either way -- the most important thing is obviously to have a figure caption that clearly explains the plot.

**Comment by nigarabbasova** [comment]
Awesome, thank you for clarifying this! :)
